### ISSUE TITLE
Python Installation Options

### ISSUE THREAD

**Issue by detlefarend** [fhswf/MLPro#130]
MLPro shall be installable in the following derivates:

- [x] **pip install mlpro**
Installs the latest release of mlpro.

- [x] **pip install mlpro[full]**
Installs mlpro and all 3rd-party packages needed in validated versions.

See also:
https://izziswift.com/what-do-square-brackets-mean-in-pip-install/

**Comment by rizkydiprasetya** [comment]
<img width="929" alt="Screenshot 2023-01-13 at 13 40 22" src="https://user-images.githubusercontent.com/75730306/212322671-365b71cb-fb46-4dbf-9946-4ad9f4c18534.png">

It seems like we need to downgrade our gym to 0.21.0 if we want to keep Stable Baselines3. Because the setuptools doesn't allow to install incompatible version.
