### ISSUE TITLE
Gym wrapper WrEnvMLPro2GYM - minor improvements

### ISSUE THREAD

**Issue by detlefarend** [fhswf/MLPro#372]
- [x] Documentation of new parameters p_new_step_api, p_render_mde
- [x] Logging of significant actions/events
- [x] Check of warnings of howto_rl_008

Related branch: wrappers

**Comment by detlefarend** [comment]
Hi Steve, after incorporating the new wrapper root class these things are left to do. Could you please take a look at it? Thx!

**Comment by steveyuwono** [comment]
Hi Detlef,  thank you for taking your time to have a look at the updates. As stated in this issue, I have adjusted some parts of our code.

Regarding the warning of how_rl_008, the first warning is due to the boundaries of action space, where Gym recommends having a range between -1 to 1. Meanwhile, in MLPro, it does not have to be within this range. However, it is just a recommendation.

The second warning has been solved. It was just because the p_new_state_api was set as 'False' by default.
