### ISSUE TITLE
Default reward strategy for reward type OVERALL

### ISSUE THREAD

**Issue by detlefarend** [fhswf/MLPro#376]
The template class Environment shall provide a default reward strategy (method _compute_reward) for reward type Reward.C_TYPE_OVERALL as follows:

Let
- s_old be the the state before the last action
- s_new be the state after the last action
- s_goal be the (current) goal state

**Proposed reward strategy:**

- **Improvement/Progress:** 
  Criterion: || s_new - s_goal || > || s_old - s_goal ||
  Reward: r = 1 / || s_new - s_goal ||
- **Worsening/Regression:**
  Criterion: || s_new - s_goal || < || s_old - s_goal ||
  Reward: r = -1 / || s_new - s_goal ||

Means: progress is rewarded positive, regression is rewarded negative.

For this the state values should be normalized.

**Comment by detlefarend** [comment]
@steveyuwono @rizkydiprasetya @marlonloeppenberg @laxmikantbaheti: Hi colleagues, what do you think of this approach? The big benefit is that we always have a strategy and don't have to care for it at the beginning. It can be redefined for a concrete environment if it doesn't work...

**Comment by marlonloeppenberg** [comment]
Hello folks,

Since I work a lot with "Reward every Action", I can say the following:

Currently "Overall" reward is already default, if you build your own system based on the class Environment (Based on the inheritance of the classes EnvBase, File models_env.py line 476)

Furthermore, I see a big problem in the often used calculation of the Overall reward --> a1*R1+a2*R2+a3*R3. Over the entire course of the training, different rewards are included in the calculation to the same extent.

Currently I don't know how it could be done better, but I'm a bit dissatisfied with the rigid reward function (especially with "every action") - difficult to handle. 

I would currently find a multi optimisation like it is used in optuna very interesting, but it also quickly becomes very complex in rl.

**Comment by detlefarend** [comment]
Hey guys, 

thanks for your feedback. Ok, basically the templates are preconfigured to faciliate a quick start for the most common use cases. In case of class Environment it is currently preconfigured for reward type OVERALL. Your own inherited class can use a different type but if you don't change something then its OVERALL. So far so good and I guess this is more or less well known.

If we have a well defined (moving) goal state then I think the proposed reward strategy is better than nothing. Currently we say 

![grafik](https://user-images.githubusercontent.com/79243976/184918818-9a274851-cb04-4825-842e-361a9b28c556.png)

that means that you always have to care for a custom reward strategy.

What I propose is to replace the "raise NotImplementedError" by the strategy above. If it is not suitable it can be redefined.

Do you think that this makes sense or is it better let the users set up everything from scratch?

**Comment by rizkydiprasetya** [comment]
> that means that you always have to care for a custom reward strategy.

This is basic knowledge of RL, they must know. So if they are planning to develop a new environment, at the beginning of the planning, they must know that they have to also develop the reward function. Because most of the cases, reward calculation is environment specific.

> The big benefit is that we always have a strategy and don't have to care for it at the beginning. It can be redefined for a concrete environment if it doesn't work...

I dont see any benefit by putting any fancy default reward calculation. Because at the end I will replace it with my own. So, I would prefer leave it as it is. If we care more about the processing action and transitioning state at the beginning other than reward, then we can put it 0.

**Comment by detlefarend** [comment]
Ok, thanks for your assessment. We will try this kind of strategy on the DP env first.
