### ISSUE TITLE
Environment "Double Pendulum"

### ISSUE THREAD

**Issue by detlefarend** [fhswf/MLPro#47]
The double pendulum problem shall be added as a benchmark environment. The mathematics and visualization of it can be adapted from [Matplotlib example "The double pendulum problem"](https://matplotlib.org/stable/gallery/animation/double_pendulum.html#sphx-glr-gallery-animation-double-pendulum-py)

Included tasks are:

- [x] 1 Preparation of new env Double Pendulum 
  - [x] Hyperparameters: gravity, pole lengths, masses, initial state
        (with senseful default settings)
  - [x] State Space: angle, velocity, acceleration of both poles and motor torque
  - [x] Kinematics adapted from Matplotlib example
  - [x] Visualization adapted from Matplotlib example
  - [x] Pseudo-implementation of reward function
- [x] 2 New Howto RL-020 - Run Double Pendulum with random agent (with default hp settings)
  - [x] Additional feature: empiric determination of boundaries of angle velocities and accelerations  
        (by running the RL scenario with data logging for state informations)
- [x] 3 DP Env: Implementation of an internal Min/Max-normalization of state values based on the found boudaries in Howto RL-020
      (separate protected method _normalize)
- [x] 4 DP Env: Planning and implementation of a suitable reward function
      A generic approach based on the distance between old/new state to the goal state (zero vector) shall be implemented. The metric of the based state space (method _distance_) shall be used - independent of the dimensinality of the state space). 
- [x] 5 Documentation on RTD

Prerequisites:
#319

**Comment by detlefarend** [comment]
Hi @budiatmadjajaWill, could you please take over this issue instead of PSM env?

**Comment by detlefarend** [comment]
No, just the link to a sample code.

**Comment by steveyuwono** [comment]
Following our meeting on 22.03.2022, here are the first tasks for @yehiaibrahim:
- [ ] Set the random initialization states inside the reset method instead of the constructor.
- [ ] Understand the environment including reset, simulation reaction, current reward structure, training procedure etc.
- [ ] Run the double pendulum training and obtain the training results
- [ ] Propose and apply different reward functions (further meetings is most likely required)

**Comment by budiatmadjajaWill** [comment]
> Following our meeting on 22.03.2022, here are the first tasks for @yehiaibrahim:
> 
> * [ ]  Set the random initialization states inside the reset method instead of the constructor.
> * [ ]  Understand the environment including reset, simulation reaction, current reward structure, training procedure etc.
> * [ ]  Run the double pendulum training and obtain the training results
> * [ ]  Propose and apply different reward functions (further meetings is most likely required)

In addition,

- [ ] Use the current Clip from the Double Pendulum Environment documentation for the Howto 22 result section
- [ ] Make new random action clip for the Double Penudulm Environment documentation

**Comment by detlefarend** [comment]
Hi @yehiaibrahim, I just added the tasks discussed last Friday.

**Comment by detlefarend** [comment]
Hi @yehiaibrahim, I extended the description of this issue. I hope that helps you to solve it. Please let @steveyuwono and/or me know if something is not clear. After determination of suitable boundaries for vel/acc and implementation of the normalization method we should talk about rewarding.

**Comment by steveyuwono** [comment]
Here are the feedbacks on the latest updates of the double pendulum environment and related howto file by @yehiaibrahim:

- [ ] You haven't changed the how to file name from 23 to 22.
- [ ] Howto 23: Line 62-67(*) is not necessary. (done) 
- [ ] Howto 23: Why do you need this Line 76-81(*) but you never use them? I don't think they are needed. (done) 
- [ ] Howto 23: Set cycle limit in Line 119(*), otherwise it will be looping forever because we don't adapt anything and always return false.
- [ ] doublependulum.py: Your normalization method of data_normalization is not correct. First, your input x is a scalar value. It means that x, x.min() and x.max() are equal for sure. You need to use 'self' to represent the instance of the class and get the boundaries from self._state_space. Third, I don't think a separate angle_normalize method is required. Fourth, 
`def _data_normalization(self, p_value, p_boundaries):
......`
- [ ] Code cleaning (done)
- [ ] We normalize the data for calculating the reward, thus it should be located in the reward function (_compute_reward) instead of _simulate_reaction (Line 317-321(*)).

(*) Refer to commit 0361b656ee645d82b247447604463229fa10be33
