### ISSUE TITLE
Bug: BF-Streams-Sklearn : Refactoring for latest changes to stream models 

### ISSUE THREAD

**Issue by laxmikantbaheti** [fhswf/MLPro#506]
**1 Describe the bug**
The default none value of feature space was not handled in sklearn

**2 To Reproduce**
1. run howto_streams_012

5.1 Operating System
   - [ ] Linux
   - [x] Windows
   - [ ] Mac OS

**Comment by detlefarend** [comment]
Hi @laxmikantbaheti, I can take over this if you like. I simply ran into a timeout this morning...

**Comment by laxmikantbaheti** [comment]
> Hi @laxmikantbaheti, I can take over this if you like. I simply ran into a timeout this morning...

Hello @detlefarend , I fixed the bug already. I just created the issue to keep history.

**Comment by detlefarend** [comment]
@laxmikantbaheti Thank you!

**Comment by detlefarend** [comment]
Hi, the code can be optimized a bit: if you rename method _set_feature_space() in _setup_feature_space() then method get_feature_space() can be removed because it's already implemented in class Stream. The label space should be set up separately in method _setup_label_space(). Maybe you could compare it with the openml implementation.
