### ISSUE TITLE
BF-Streams: Native stream for csv data files

### ISSUE THREAD

**Issue by detlefarend** [fhswf/MLPro#575]
**Description/Motivation**
A native Stream class shall be implemented that provides data records of a csv file as a sequence of instances. The names of the features can optionally be extracted from the first row of the file (header information).

**Task list**
- [ ] 1. New module csv_file.py
- [ ] 2. New class StreamMLProCSV
- [ ] 3. Example file
- [ ] 4. Howto

**Related issues**
#...

**Cross references**
class DataStoring

**Comment by steveyuwono** [comment]
Hi @detlefarend and @laxmikantbaheti ,

last week I added the first version of StreamMLProCSV, where the source code can be found in the following path: MLPro/src/mlpro/bf/streams/streams/csv_file.py. I also set up a how-to file, namely [howto_bf_streams_002_accessing_data_from_csv_files.py](https://github.com/fhswf/MLPro/blob/online_adaptivity12/src/mlpro/bf/examples/howto_bf_streams_002_accessing_data_from_csv_files.py).

I have also enhanced a little bit the DataStoring base class, so that it can detect whether the CSV contains the feature/label name in the first row as well as the frame in the first column. Then, I use the DataStoring class to load the CSV file before being processed as a data stream.

I have a question, is it correct to place the csv_file.py in the current path or should it be located in another sub-folder? If it is correct, then I will proceed with the documentation. Thank you.

**Comment by detlefarend** [comment]
> I have a question, is it correct to place the csv_file.py in the current path or should it be located in another sub-folder? If it is correct, then I will proceed with the documentation. Thank you.

Hi @steveyuwono: completely fine!

**Comment by detlefarend** [comment]
@steveyuwono This is done, isn't it?

**Comment by steveyuwono** [comment]
> @steveyuwono This is done, isn't it?

Yes, this is done

**Comment by detlefarend** [comment]
Hi @steveyuwono, could you please assign the related pull request (even if it's already done) and set it to done? Then it is reachable by forward navigation from the release notes. Thank you!

**Comment by steveyuwono** [comment]
> Hi @steveyuwono, could you please assign the related pull request (even if it's already done) and set it to done? Then it is reachable by forward navigation from the release notes. Thank you!

Alright, done
