### ISSUE TITLE
Bug: Unit Test Failed for Ubuntu due to River

### ISSUE THREAD

**Issue by steveyuwono** [fhswf/MLPro#871]
**1 Describe the bug**
The unit test failed due to the inability to install the River package, as seen in the screenshot in point 4. This behaviour specifically happens in Ubuntu-based tests. Windows and MacOS tests are functioning properly.

**2 To Reproduce**
Steps to reproduce the behaviour:
Create a new branch (or select any development branches) and run the unit test

**3 Expected behavior**
Unit test failed

**4 Screenshots**
![image](https://github.com/fhswf/MLPro/assets/88610818/a5369146-046b-4411-b914-e05cfff92eba)
![image](https://github.com/fhswf/MLPro/assets/88610818/125961d1-f498-47d8-a0f2-6a43036ea6e5)

**5 Additional Information**

5.1 Operating System
   - [x] Linux
   - [ ] Windows
   - [ ] Mac OS

**Comment by detlefarend** [comment]
Hi guys, It is possibly the outdated pip version within the ubuntu platform. I'll take a closer look later and try to fix it...

**Comment by detlefarend** [comment]
@steveyuwono  @syamrajsatheesh: Hi guys, the problem is solved for the moment. Origin of the problem is the current version 0.20.1 of river that can not be installed under Ubuntu. I excluded exactly this version from our validation procedures. Currently, version 0.19.0 is used for unit tests. Future versions of river will be used again so that the problem can occur again...
