### ISSUE TITLE
Bug: Howtos oa_ca_001/002 raise exceptions

### ISSUE THREAD

**Issue by detlefarend** [fhswf/MLPro#881]
**1 Describe the bug**
The howtos oa_ca_001/002 raise exceptions.

**2 To Reproduce**
1. Open branch oa/streams/basics
2. Remove '.off' from the file names
3. Run the howtos

**3 Expected behavior**
...

**4 Screenshots**
![grafik](https://github.com/fhswf/MLPro/assets/79243976/60aca39d-b7f1-4bdf-b8d5-6f727d6498cc)

**5 Additional Informations**
I enabled the visualization of centroid-based clusters in #882. I would like to use the same howtos for validation. In the best case the centroid of each cluster is shown as a point with a velocity vector...

5.1 Operating System
   - [ ] Linux
   - [x] Windows
   - [ ] Mac OS

**Comment by detlefarend** [comment]
Hi @steveyuwono, the exception was caused by a program error in class BoundaryDetector (see #884). This fixed and both howtos run again. I also turned on visualization/logging of the wrapper task t3 but the centroid visualization still doesn't work. Could you please check whether the visualization parameter is handed over to each cluster within the wrapper? Thx!

**Comment by detlefarend** [comment]
Hi @steveyuwono, a further hint: both howtos still cause exceptions during the unit test. It seems that something fails in backend mode only. See also: https://github.com/fhswf/MLPro/actions/runs/6922668113/job/18829669998

**Comment by steveyuwono** [comment]
Good morning @detlefarend , I have updated the River wrapper classes for cluster analyzers to allow visualization. As shown in the image below, each centroid has a separate graphical window. Is this correct? Just to make sure, because from what I remember in the last meeting, you would like to integrate them with the previous figure or all of them in one figure.

![image](https://github.com/fhswf/MLPro/assets/88610818/3323d716-4408-40ed-9024-536e5b60ed44)

Also in the video below, I illustrate the changes for the centre of a cluster in our visualization, it seems that the point is correctly shifted but the red arrow does not show the correct direction.

https://github.com/fhswf/MLPro/assets/88610818/221aeef5-dbea-4194-9e41-3ff7b03f2d9f

Moreover, the unit test failed due to both howtos being fixed and the windowing task has been added to howto with dynamic 3d point clouds.

**Comment by detlefarend** [comment]
Hi @steveyuwono, as you mentioned the clusters are intended to be shown in the predecissor window. There is an internal attribute to control this. It seems that it is missing in class Cluster. I'll take a look and come back with my findings...
